title: Marlon Smith
logo: /Assets/img/resized_headshot_circle.png
description: Myrtle Beach, South Carolina
description: [View Website](https://smithmarlo.github.io/personal-website/)
theme: jekyll-theme-minimal 
